services:
  api:
    build: ./
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network

  postgres_db:
    image: postgres
    container_name: sk-dev-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  postgres-db-volume:

networks:
  app-network:
    external: true